FROM python:3.11-slim

WORKDIR /app

# Копируем необходимые файлы
COPY requirements.txt .
COPY bot.py .
COPY .env .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Запускаем бота
CMD ["python", "bot.py"] 